tech:
  xavi:
    soulsync:
      cfg-file: soulsync-cfg.properties
      gateway:
        request:
          spotify:
            tracks-per-playlist: 20
        base-url:
          spotify:
            auth: https://accounts.spotify.com
            main: https://api.spotify.com
        path:
          spotify:
            auth:
              get-token:
                ep: /api/token
            main:
              get-tracks:
                ep: /v1/playlists/{playlistId}/tracks
              get-playlist-data:
                ep: /v1/playlists/{playlistId}/
              get-cover:
                ep: /v1/playlists/{playlistId}/images
          slskd:
            health: /health
            login: /api/v0/session
            search: /api/v0/searches
            responses: /responses
            download: /api/v0/transfers/downloads
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soulsync?currentSchema=public&ssl=false
    username: soulsync
    password: soulsync
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
  security:
    user:
      password: none

logging:
  level:
    com:
      mashape:
        unirest: DEBUG
      fasterxml:
        jackson:
          databind: DEBUG
    org:
      hibernate:
        SQL: DEBUG
    root: INFO