tech:
  xavi:
    soulsync:
      cfg:
        max-req-tracks-per-playlist: 20
        wait-sec-btw-result-req: 10
        max-retries-result-req: 10
        delay-ms: 5000
        common-words-to-remove: the,a,an,and,feat,with,of,in,on,at,by,for,to
        accepted-formats: mp3
        min-mp3-bitrate: 100
        interval-minutes-scheduled-task: 1
        max-songs-downloading-at-a-time: 5
        avoid-repeating-errored-file: true
      credentials:
        spotify:
          client-id: id
          client-secret: sec
        slskd:
          username: slskd
          password: slskd
      gateway:
        base-url:
          spotify:
            auth: https://accounts.spotify.com
            main: https://api.spotify.com
          slskd:
            main: http://localhost:5030
        path:
          spotify:
            auth:
              get-token:
                ep: /api/token
            main:
              get-tracks:
                ep: /v1/playlists/{playlistId}/tracks
              get-playlist-data:
                ep: /v1/playlists/{playlistId}/
              get-cover:
                ep: /v1/playlists/{playlistId}/images
          slskd:
            health: /health
            login: /api/v0/session
            search: /api/v0/searches
            responses: /responses
            download: /api/v0/transfers/downloads
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soulsync?currentSchema=public&ssl=false
    username: soulsync
    password: soulsync
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
  security:
    user:
      password: none

logging:
  level:
    com:
      mashape:
        unirest: DEBUG
      fasterxml:
        jackson:
          databind: DEBUG
    org:
      hibernate:
        SQL: DEBUG