tech.xavi.soulsync.cfg.api.spotify.client-id=id
tech.xavi.soulsync.cfg.api.spotify.client-secret=sec
tech.xavi.soulsync.cfg.api.slskd.username=slskd
tech.xavi.soulsync.cfg.api.slskd.password=slskd
tech.xavi.soulsync.cfg.api.slskd.url=http://localhost:5030
tech.xavi.soulsync.cfg.finder.common-words-to-remove=the,a,an,and,feat,with,of,in,on,at,by,for,to
tech.xavi.soulsync.cfg.finder.accepted-formats=mp3
tech.xavi.soulsync.cfg.finder.min-mp3-bitrate=100
tech.xavi.soulsync.cfg.finder.avoid-repeat-file-when-error=true
tech.xavi.soulsync.cfg.app.total-simultaneous-processes=5
tech.xavi.soulsync.cfg.app.max-songs-downloading-same-time=5
tech.xavi.soulsync.cfg.app.wait-sec-btw-result-req=10
tech.xavi.soulsync.cfg.app.max-retries-wait-result=10
tech.xavi.soulsync.cfg.app.delay-ms=5000
tech.xavi.soulsync.cfg.app.interval-minutes-scheduled-task=5
