version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: soulsync
      POSTGRES_PASSWORD: soulsync
      POSTGRES_DB: soulsync

  be:
    container_name: be
    image: soulsync-bot:1.0.0
    build: 
      context: ../BACKEND
      dockerfile: Dockerfile
    environment:
      - SOULSYNC_DATASOURCE_URL=jdbc:postgresql://db:5432/soulsync?currentSchema=public&ssl=false
      - SOULSYNC_DATASOURCE_USER=soulsync
      - SOULSYNC_DATASOURCE_PASS=soulsync
    ports:
      - 14947:14947
    depends_on:
      - db

  fe:
    container_name: fe
    build:
      context: ../FRONTEND
      dockerfile: Dockerfile
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:14947
    ports:
      - "7316:7316"
  
  # slskd:
  #   container_name: slskd
  #   image: slskd/slskd
  #   ports:
  #     - "5030:5030"
  #     - "5031:5031"
  #     - "50300:50300"
  #   environment:
  #     - SLSKD_REMOTE_CONFIGURATION=true
  #   volumes:
  #     - /app:/app
  #   restart: always
  #   soulseek:
  #    username: soulsyncbot
  #    password: soulsyncbot
