server:
  port: 6743
  error:
    path: /redirect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soulsync?currentSchema=public&ssl=false
    username: soulsync
    password: soulsync
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: utf8

tech:
  xavi:
    soulsync:
      cfg:
        default:
          search-policy:
            sp-file-formats: mp3
            sp-min-chars-per-word: 3
            sp-words-to-remove: the,a,an,and,feat,with,of,in,on,at,by,for,to,featuring
            sp-min-mp3-bitrate: 320
            sp-minimum-mins-retry: 60
            sp-max-retries: 0
            sp-is-avoid-remix: true
            sp-is-avoid-live: true
          application:
            app-auto-pause-adjustment: true
            app-max-simultaneous-threads: 5
            app-tracks-per-queue: 100
            app-search-waiting-seconds: 60
            app-total-records-per-batch: 50
            app-maintenance-task-interval-mins: 5
            app-minutes-to-evaluate-as-stuck: 60
      gateway:
        base-url:
          spotify:
            auth: https://accounts.spotify.com
            main: https://api.spotify.com
        path:
          spotify:
            auth:
              get-token:
                ep: /api/token
            playlist:
              get-playlist:
                ep: /v1/playlists/{playlistId}
            artist:
              get-discography:
                ep: /v1/artists/{artistId}/albums
            album:
              get-album:
                ep: /v1/albums
          slskd:
            health: /api/v0/session/enabled
            login: /api/v0/session
            search: /api/v0/searches
            downloads: /api/v0/transfers/downloads

logging:
  level:
    tech.xavi.soulsync: TRACE
    org.springframework.web.client.RestTemplate: INFO
    com.fasterxml.jackson: INFO
