server:
  port: 14947
tech:
  xavi:
    soulsync:
      cors-origin: http://localhost:1337
      demo-mode:
        enabled: true
        stamp-threshold: 1705788680000
        downloads-directory: /home/xavi/slskd/app/downloads
      jwt:
        issuer: SoulSyncAPI
        token:
          exp-sec: 86400000
      gateway:
        base-url:
          spotify:
            auth: https://accounts.spotify.com
            main: https://api.spotify.com
        path:
          spotify:
            auth:
              get-token:
                ep: /api/token
            playlist:
              get-tracks:
                ep: /v1/playlists/{playlistId}/tracks
              get-playlist-data:
                ep: /v1/playlists/{playlistId}/
              get-cover:
                ep: /v1/playlists/{playlistId}/images
            artist:
              get-albums:
                ep: /v1/artists/{artistId}/albums
            album:
              get-tracks:
                ep: /v1/albums/{albumId}/
          slskd:
            health: /health
            login: /api/v0/session
            search: /api/v0/searches
            responses: /responses
            download: /api/v0/transfers/downloads

spring:
  datasource:
    url: ${SOULSYNC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/soulsync?currentSchema=public&ssl=false}
    username: ${SOULSYNC_DATASOURCE_USER:soulsync}
    password: ${SOULSYNC_DATASOURCE_PASS:soulsync}
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
      #ddl-auto: create-drop
  security:
    user:
      password: none

logging:
  level:
    com:
      fasterxml:
        jackson:
          databind: INFO
    org:
      hibernate:
        SQL: INFO