server:
  port: 6743
  error:
    path: /redirect

spring:
  datasource:
    url: ${SOULSYNC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/soulsync?currentSchema=public&ssl=false}
    username: ${SOULSYNC_DATASOURCE_USER:soulsync}
    password: ${SOULSYNC_DATASOURCE_PASS:soulsync}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        connection:
          characterEncoding: utf8
    show-sql: false

tech:
  xavi:
    soulsync:
      version: @revision@
      cfg:
        login-attempt:
          max-try: 5
          block-time-min: 15
        default:
          search-policy:
            sp-file-formats: mp3
            sp-min-chars-per-word: 3
            sp-words-to-remove: the,a,an,and,feat,with,of,in,on,at,by,for,to,featuring
            sp-min-mp3-bitrate: 320
            sp-minimum-mins-retry: 60
            sp-max-retries: 0
            sp-is-avoid-remix: true
            sp-is-avoid-live: true
            sp-is-avoid-radio-edit: true
            sp-is-avoid-mixed-track: true
          search:
            srch-millis-between-requests: 2000
            srch-max-simultaneous-threads: 5
            srch-tracks-per-queue: 100
            srch-search-waiting-seconds: 60
            srch-minutes-to-evaluate-as-stuck: 60
          maintenance:
            app-data-refresh-rate: 30
            app-run-download-task: true
            app-run-maintenance-task: true
            app-maintenance-task-interval-mins: 5
            app-is-relocate: false
            app-slskd-downloads-path: /soulsync/slskd-downloads
            app-relocated-files-path: /soulsync/relocated
            app-relocate-by: PLAYLIST
            app-rename-relocated: false
            app-move-or-copy: COPY
      gateway:
        base-url:
          spotify:
            auth: https://accounts.spotify.com
            main: https://api.spotify.com
          github: https://api.github.com
        path:
          github:
            release: /repos/xaviqo/SoulSyncBot/releases/latest
          spotify:
            auth:
              get-token:
                ep: /api/token
            playlist:
              get-playlist:
                ep: /v1/playlists/{playlistId}
            artist:
              get-discography:
                ep: /v1/artists/{artistId}/albums
            album:
              get-album:
                ep: /v1/albums
          slskd:
            health: /api/v0/session/enabled
            login: /api/v0/session
            search: /api/v0/searches
            downloads: /api/v0/transfers/downloads
            reboot: /api/v1/application

logging:
  level:
    tech.xavi.soulsync: INFO
    org.springframework.web.client.RestTemplate: INFO
    com.fasterxml.jackson: INFO
